SOURCES += $(wildcard Graphics_Systems/Direct3D11/*.cpp) $(wildcard Graphics_Systems/General/*.cpp)
override CPPFLAGS += -DINITGUID -DD3D_COMPILER_VERSION=47
override LDLIBS += -ldxgi -ld3d11 -lD3DCompiler
