include ../../../../../../Unix.mk
ifeq ($(UNIX_BASED), true)
	SOURCES += Universal_System/Extensions/IniFilesystem/UNIXiniindex.cpp
	SOURCES += Universal_System/Extensions/IniFilesystem/UNIXinifs.cpp
else
	SOURCES += Universal_System/Extensions/IniFilesystem/WINDOWSinifs.cpp
endif
