SHARED_SRC_DIR := ../../shared
override CXXFLAGS += -I$(SHARED_SRC_DIR)/apiprocess -std=c++17
override CFLAGS += -I$(SHARED_SRC_DIR)/apiprocess -std=c++17
SOURCES += Universal_System/Extensions/ShellExecution/shell.cpp
