SHARED_SRC_DIR := ../../shared
override CXXFLAGS += -I$(SHARED_SRC_DIR) -std=c++17 $(shell pkg-config --cflags sdl2)
override CFLAGS += -I$(SHARED_SRC_DIR) -std=c++17 $(shell pkg-config --cflags sdl2)
SOURCES += Universal_System/Extensions/ShellExecution/shell.cpp
