include Graphics_Systems/OpenGL/Makefile
SOURCES += $(wildcard Graphics_Systems/OpenGL2/*.cpp)

VERTEX_SHADER_PREFIX := Graphics_Systems/OpenGL2/vertex_shader_prefix.glsl
VERTEX_SHADER := Graphics_Systems/OpenGL2/vertex_shader.glsl
FRAGMENT_SHADER_PREFIX := Graphics_Systems/OpenGL2/fragment_shader_prefix.glsl
FRAGMENT_SHADER := Graphics_Systems/OpenGL2/fragment_shader.glsl
