include Graphics_Systems/OpenGL/Makefile
include Graphics_Systems/OpenGL2-OpenGLES2/Makefile
SOURCES += $(wildcard Graphics_Systems/OpenGL2/*.cpp)

SHADER_VERSION := Graphics_Systems/OpenGL2/version.glsl
