SHARED_SRC_DIR := ../../shared
override CXXFLAGS += -I$(SHARED_SRC_DIR)/libpng-util
override LDLIBS += -L$(SHARED_SRC_DIR)/libpng-util -lpng-util -lpng -lz

SOURCES += Universal_System/Extensions/libpng/libpng-ext.cpp
