coverage:
  precision: 2
  round: down
  range: "50...100"

  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
    changes:
      default: off

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true
  require_base: no
  require_head: yes
