#!/bin/sh
cd "${0%/*}";
if [ `uname` = "Darwin" ]; then
  env PATH=$PATH:/opt/homebrew/bin make -C "." Game WORKDIR="./stigma/" CODEGEN="./stigma/" CFLAGS="-I./stigma" CXXFLAGS="-I./stigma" GMODE="Compile" GRAPHICS="OpenGL1" AUDIO="SDL" COLLISION="Precise" WIDGETS="None" NETWORKING="None" PLATFORM="SDL" TARGET-PLATFORM="MacOSX" CC="clang" CXX="clang++" MAKE="make" COMPILEPATH="MacOSX/MacOSX/Clang" EXTENSIONS=" Universal_System/Extensions/HideErrors Universal_System/Extensions/Alarms Universal_System/Extensions/Paths" OUTPUTNAME="${0%/*}/build/Key to Success"
elif [ $(uname) = "Linux" ]; then
  make -C "." Game WORKDIR="./stigma/" CODEGEN="./stigma/" CFLAGS="-I./stigma" CXXFLAGS="-I./stigma" GMODE="Compile" GRAPHICS="OpenGL1" AUDIO="SDL" COLLISION="Precise" WIDGETS="None" NETWORKING="None" PLATFORM="SDL" TARGET-PLATFORM="Linux" CC="gcc" CXX="g++" MAKE="make" COMPILEPATH="Linux/Linux/GCC" EXTENSIONS=" Universal_System/Extensions/HideErrors Universal_System/Extensions/Alarms Universal_System/Extensions/Paths" OUTPUTNAME="${0%/*}/build/Key to Success"
elif [ $(uname) = "FreeBSD" ]; then
  make -C "." Game WORKDIR="./stigma/" CODEGEN="./stigma/" CFLAGS="-I./stigma" CXXFLAGS="-I./stigma" GMODE="Compile" GRAPHICS="OpenGL1" AUDIO="SDL" COLLISION="Precise" WIDGETS="None" NETWORKING="None" PLATFORM="SDL" TARGET-PLATFORM="FreeBSD" CC="clang" CXX="clang++" MAKE="make" COMPILEPATH="FreeBSD/FreeBSD/Clang" EXTENSIONS=" Universal_System/Extensions/HideErrors Universal_System/Extensions/Alarms Universal_System/Extensions/Paths" OUTPUTNAME="${0%/*}/build/Key to Success"
elif [ $(uname) = "DragonFly" ]; then
  make -C "." Game WORKDIR="./stigma/" CODEGEN="./stigma/" CFLAGS="-I./stigma" CXXFLAGS="-I./stigma" GMODE="Compile" GRAPHICS="OpenGL1" AUDIO="SDL" COLLISION="Precise" WIDGETS="None" NETWORKING="None" PLATFORM="SDL" TARGET-PLATFORM="DragonFlyBSD" CC="gcc" CXX="g++" MAKE="make" COMPILEPATH="DragonFlyBSD/DragonFlyBSD/GCC" EXTENSIONS=" Universal_System/Extensions/HideErrors Universal_System/Extensions/Alarms Universal_System/Extensions/Paths" OUTPUTNAME="${0%/*}/build/Key to Success"
elif [ $(uname) = "OpenBSD" ]; then
  make -C "." Game WORKDIR="./stigma/" CODEGEN="./stigma/" CFLAGS="-I./stigma" CXXFLAGS="-I./stigma" GMODE="Compile" GRAPHICS="OpenGL1" AUDIO="OpenAL" COLLISION="Precise" WIDGETS="None" NETWORKING="None" PLATFORM="OpenAL" TARGET-PLATFORM="OpenBSD" CC="clang" CXX="clang++" MAKE="make" COMPILEPATH="OpenBSD/OpenBSD/Clang" EXTENSIONS=" Universal_System/Extensions/HideErrors Universal_System/Extensions/Alarms Universal_System/Extensions/Paths" OUTPUTNAME="${0%/*}/build/Key to Success"
else
  make -C "." Game WORKDIR="./stigma/" CODEGEN="./stigma/" CFLAGS="-I./stigma" CXXFLAGS="-I./stigma" LDFLAGS="-static-libgcc -static-libstdc++ -static" LDLIBS="-static-libgcc -static-libstdc++ -static" GMODE="Compile" GRAPHICS="OpenGL1" AUDIO="SDL" COLLISION="Precise" WIDGETS="None" NETWORKING="None" PLATFORM="SDL" TARGET-PLATFORM="Windows" CC="gcc" CXX="g++" MAKE="make" COMPILEPATH="Windows/Windows/GCC" EXTENSIONS=" Universal_System/Extensions/HideErrors Universal_System/Extensions/Alarms Universal_System/Extensions/Paths" OUTPUTNAME="${0%/*}/build/Key to Success.exe"
fi
