override CXXFLAGS += -IGraphics_Systems/OpenGL2-OpenGLES2/
SOURCES += $(wildcard Graphics_Systems/OpenGL2-OpenGLES2/*.cpp)

SHADER_FOLDER := Graphics_Systems/OpenGL2-OpenGLES2/shaders
VERTEX_SHADER_PREFIX := $(SHADER_FOLDER)/vertex_shader_prefix.glsl
VERTEX_SHADER := $(SHADER_FOLDER)/vertex_shader.glsl
FRAGMENT_SHADER_PREFIX := $(SHADER_FOLDER)/fragment_shader_prefix.glsl
FRAGMENT_SHADER := $(SHADER_FOLDER)/fragment_shader.glsl
