#include "../Window.h"
#include "Platforms/xlib/XLIBicon.h"
#include "Platforms/General/PFwindow.h"
#include "Platforms/General/PFmain.h"
#include "Platforms/General/PFfilemanip.h"
#include "Universal_System/Resources/sprites.h"
#include "Universal_System/Resources/background.h"
