override CFLAGS += -I/opt/local/include
override CXXFLAGS += -I/opt/local/include
override LDLIBS += -L/opt/local/lib
override LDFLAGS += -L/opt/local/lib
SOURCES += $(wildcard Bridges/OpenGL/*.cpp)
