/********************************************************************************\
**                                                                              **
**  Copyright (C) 2008 Josh Ventura                                             **
**                                                                              **
**  This file is a part of the ENIGMA Development Environment.                  **
**                                                                              **
**                                                                              **
**  ENIGMA is free software: you can redistribute it and/or modify it under the **
**  terms of the GNU General Public License as published by the Free Software   **
**  Foundation, version 3 of the license or any later version.                  **
**                                                                              **
**  This application and its source code is distributed AS-IS, WITHOUT ANY      **
**  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS   **
**  FOR A PARTICULAR PURPOSE. See the GNU General Public License for more       **
**  details.                                                                    **
**                                                                              **
**  You should have recieved a copy of the GNU General Public License along     **
**  with this code. If not, see <http://www.gnu.org/licenses/>                  **
**                                                                              **
**  ENIGMA is an environment designed to create games and other programs with a **
**  high-level, fully compilable language. Developers of ENIGMA or anything     **
**  associated with ENIGMA are in no way responsible for its users or           **
**  applications created by its users, or damages caused by the environment     **
**  or programs made in the environment.                                        **
**                                                                              **
\********************************************************************************/

//This file was generated by the ENIGMA Development Environment.
//Editing it is a sign of a certain medical condition. We're not sure which one.

namespace enigma {

void extensions_initialize() {
}

} // namespace enigma

evariant roomprecreate0()
{
  
  return 0;
}

evariant roomcreate0()
{
;
  
  return 0;
}
evariant roomprecreate1()
{
  
  return 0;
}

evariant roomcreate1()
{
;
  
  return 0;
}
evariant roomprecreate2()
{
  
  return 0;
}

evariant roomcreate2()
{
;
  
  return 0;
}
evariant roomprecreate3()
{
  
  return 0;
}

evariant roomcreate3()
{
;
  
  return 0;
}
evariant roomprecreate4()
{
  
  return 0;
}

evariant roomcreate4()
{
;
  
  return 0;
}
evariant roomprecreate5()
{
  
  return 0;
}

evariant roomcreate5()
{
;
  
  return 0;
}
evariant roomprecreate6()
{
  
  return 0;
}

evariant roomcreate6()
{
;
  
  return 0;
}
evariant roomprecreate7()
{
  
  return 0;
}

evariant roomcreate7()
{
;
  
  return 0;
}
evariant roomprecreate8()
{
  
  return 0;
}

evariant roomcreate8()
{
;
  
  return 0;
}
evariant roomprecreate9()
{
  
  return 0;
}

evariant roomcreate9()
{
;
  
  return 0;
}
evariant roomprecreate10()
{
  
  return 0;
}

evariant roomcreate10()
{
;
  
  return 0;
}
evariant roomprecreate11()
{
  
  return 0;
}

evariant roomcreate11()
{
;
  
  return 0;
}
