/********************************************************************************\
**                                                                              **
**  Copyright (C) 2008 Josh Ventura                                             **
**                                                                              **
**  This file is a part of the ENIGMA Development Environment.                  **
**                                                                              **
**                                                                              **
**  ENIGMA is free software: you can redistribute it and/or modify it under the **
**  terms of the GNU General Public License as published by the Free Software   **
**  Foundation, version 3 of the license or any later version.                  **
**                                                                              **
**  This application and its source code is distributed AS-IS, WITHOUT ANY      **
**  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS   **
**  FOR A PARTICULAR PURPOSE. See the GNU General Public License for more       **
**  details.                                                                    **
**                                                                              **
**  You should have recieved a copy of the GNU General Public License along     **
**  with this code. If not, see <http://www.gnu.org/licenses/>                  **
**                                                                              **
**  ENIGMA is an environment designed to create games and other programs with a **
**  high-level, fully compilable language. Developers of ENIGMA or anything     **
**  associated with ENIGMA are in no way responsible for its users or           **
**  applications created by its users, or damages caused by the environment     **
**  or programs made in the environment.                                        **
**                                                                              **
\********************************************************************************/

//This file was generated by the ENIGMA Development Environment.
//Editing it is a sign of a certain medical condition. We're not sure which one.

#ifndef NEW_OBJ_PREFIX
#  define NEW_OBJ_PREFIX
#endif

case 0:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_splash_screen(x,y,idn);
  break;
case 1:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_title_logo(x,y,idn);
  break;
case 2:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_copyright(x,y,idn);
  break;
case 3:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_love(x,y,idn);
  break;
case 4:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_door_top(x,y,idn);
  break;
case 5:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_door_bottom(x,y,idn);
  break;
case 6:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_doorknob(x,y,idn);
  break;
case 7:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_doorway_ver(x,y,idn);
  break;
case 8:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_doorway_hor(x,y,idn);
  break;
case 9:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_doorway_corner_left(x,y,idn);
  break;
case 10:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_doorway_corner_right(x,y,idn);
  break;
case 11:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_doorway_bottom(x,y,idn);
  break;
case 12:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_background_shark(x,y,idn);
  break;
case 13:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_controller(x,y,idn);
  break;
case 14:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_background(x,y,idn);
  break;
case 15:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_character(x,y,idn);
  break;
case 16:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_charlittle(x,y,idn);
  break;
case 17:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_char_win(x,y,idn);
  break;
case 18:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_char_lose(x,y,idn);
  break;
case 19:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_charlittle_die(x,y,idn);
  break;
case 20:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_baddie_parent(x,y,idn);
  break;
case 21:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_land_parent(x,y,idn);
  break;
case 22:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_water_parent(x,y,idn);
  break;
case 23:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_key(x,y,idn);
  break;
case 24:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_door(x,y,idn);
  break;
case 25:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_sparkle(x,y,idn);
  break;
case 26:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_sparklittle(x,y,idn);
  break;
case 27:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_ladder(x,y,idn);
  break;
case 28:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_water_outline(x,y,idn);
  break;
case 29:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_water_top(x,y,idn);
  break;
case 30:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_water_base(x,y,idn);
  break;
case 31:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_paused(x,y,idn);
  break;
case 32:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_brick(x,y,idn);
  break;
case 33:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_brick_hor(x,y,idn);
  break;
case 34:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_brick_ver(x,y,idn);
  break;
case 35:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_brick_mid(x,y,idn);
  break;
case 36:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_baddie_destroy_acid(x,y,idn);
  break;
case 37:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_baddie_acid_leak(x,y,idn);
  break;
case 38:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_baddie_acid_drop(x,y,idn);
  break;
case 39:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_baddie_acid_man(x,y,idn);
  break;
case 40:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_baddie_spikes_up(x,y,idn);
  break;
case 41:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_baddie_spikes_down(x,y,idn);
  break;
case 42:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_baddie_barrier(x,y,idn);
  break;
case 43:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_wood(x,y,idn);
  break;
case 44:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_wood_hor(x,y,idn);
  break;
case 45:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_wood_ver(x,y,idn);
  break;
case 46:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_wood_mid(x,y,idn);
  break;
case 47:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_baddie_destroy_trap(x,y,idn);
  break;
case 48:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_baddie_trap_up_gen(x,y,idn);
  break;
case 49:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_baddie_trap_down_gen(x,y,idn);
  break;
case 50:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_baddie_trap_left_gen(x,y,idn);
  break;
case 51:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_baddie_trap_right_gen(x,y,idn);
  break;
case 52:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_baddie_trap_up(x,y,idn);
  break;
case 53:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_baddie_trap_down(x,y,idn);
  break;
case 54:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_baddie_trap_left(x,y,idn);
  break;
case 55:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_baddie_trap_right(x,y,idn);
  break;
case 56:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_window(x,y,idn);
  break;
case 57:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_coral(x,y,idn);
  break;
case 58:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_coral_hor(x,y,idn);
  break;
case 59:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_coral_ver(x,y,idn);
  break;
case 60:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_coral_mid(x,y,idn);
  break;
case 61:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_baddie_shark(x,y,idn);
  break;
case 62:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_rock(x,y,idn);
  break;
case 63:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_rock_hor(x,y,idn);
  break;
case 64:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_rock_ver(x,y,idn);
  break;
case 65:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_rock_mid(x,y,idn);
  break;
case 66:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_rock_hor_large(x,y,idn);
  break;
case 67:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_rock_ver_large(x,y,idn);
  break;
case 68:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_rock_mid_large(x,y,idn);
  break;
case 69:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_rock_mid_large_hor(x,y,idn);
  break;
case 70:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_rock_mid_large_ver(x,y,idn);
  break;
case 71:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_baddie_buzz_saw_1(x,y,idn);
  break;
case 72:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_baddie_buzz_saw_2(x,y,idn);
  break;
case 73:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_baddie_buzz_saw_3(x,y,idn);
  break;
case 74:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_baddie_buzz_saw_4(x,y,idn);
  break;
case 75:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_baddie_buzz_saw_5(x,y,idn);
  break;
case 76:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_baddie_buzz_saw_6(x,y,idn);
  break;
case 77:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_baddie_spike_ball_small_left(x,y,idn);
  break;
case 78:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_baddie_spike_ball_small_right(x,y,idn);
  break;
case 79:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_baddie_spike_ball_large_left(x,y,idn);
  break;
case 80:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_baddie_spike_ball_large_right(x,y,idn);
  break;
case 81:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_baddie_fire(x,y,idn);
  break;
case 82:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_baddie_lava(x,y,idn);
  break;
case 83:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_baddie_fire_ball_short(x,y,idn);
  break;
case 84:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_baddie_fire_ball_tall(x,y,idn);
  break;
case 85:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_game_win(x,y,idn);
  break;
case 86:
    NEW_OBJ_PREFIX new enigma::OBJ_obj_game_lose(x,y,idn);
  break;


#undef NEW_OBJ_PREFIX
