#!/bin/sh
# build shared library
cd "${0%/*}"
if [ `uname` = "Darwin" ]; then
 clang++ "/opt/local/lib/libSDL2.a" "ImFileDialog.cpp" "imgui.cpp" "imgui_impl_sdl.cpp" "imgui_impl_sdlrenderer.cpp" "imgui_draw.cpp" "imgui_tables.cpp" "imgui_widgets.cpp" "msgbox/imguial_msgbox.cpp" "../../../../shared/apifilesystem/filesystem.cpp" "filedialogs.cpp" -o "/tmp/stigma.dylib" -std=c++17 -DIFD_SHARED_LIBRARY -shared -I../../../../shared/apifilesystem -I../../../../shared -Wno-format-security -I. -DIMGUI_USE_WCHAR32 -I/opt/local/include -I/opt/local/include/SDL2 -std=c++17 -DIFD_SHARED_LIBRARY -shared -I../../../../shared/apifilesystem -I../../../../shared -Wno-format-security -ObjC++ -liconv -Wl,-framework,CoreAudio -Wl,-framework,AudioToolbox -Wl,-weak_framework,CoreHaptics -Wl,-weak_framework,GameController -Wl,-framework,ForceFeedback -lobjc -Wl,-framework,CoreVideo -Wl,-framework,Cocoa -Wl,-framework,Carbon -Wl,-framework,IOKit -Wl,-weak_framework,QuartzCore -Wl,-weak_framework,Metal -fPIC -arch arm64 -arch x86_64 -fPIC
elif [ $(uname) = "Linux" ]; then
 g++ "ImFileDialog.cpp" "imgui.cpp" "imgui_impl_sdl.cpp" "imgui_impl_opengl2.cpp" "imgui_draw.cpp" "imgui_tables.cpp" "imgui_widgets.cpp" "msgbox/imguial_msgbox.cpp" "../../../../shared/apifilesystem/filesystem.cpp" "filedialogs.cpp" "../../../../shared/lunasvg/liblunasvg.a" -o "/tmp/stigma.so" -std=c++17 -DIFD_SHARED_LIBRARY -shared -I../../../../shared/apifilesystem -I../../../../shared -Wno-format-security -I. -L../../../../shared/lunasvg -DIMGUI_USE_WCHAR32 -static-libgcc -static-libstdc++ `pkg-config --cflags --libs sdl2 --static` `pkg-config --cflags --libs gtk+-3.0` `pkg-config --cflags --libs gio-2.0` `pkg-config --cflags --libs glib-2.0` -lX11 -lGL -lpthread -fPIC
elif [ $(uname) = "FreeBSD" ]; then
 clang++ "ImFileDialog.cpp" "imgui.cpp" "imgui_impl_sdl.cpp" "imgui_impl_opengl2.cpp" "imgui_draw.cpp" "imgui_tables.cpp" "imgui_widgets.cpp" "msgbox/imguial_msgbox.cpp" "../../../../shared/apifilesystem/filesystem.cpp" "filedialogs.cpp" "../../../../shared/lunasvg/liblunasvg.a" -o "/tmp/stigma.so" -std=c++17 -DIFD_SHARED_LIBRARY -shared -I../../../../shared/apifilesystem -I../../../../shared -Wno-format-security -I. -L../../../../shared/lunasvg -DIMGUI_USE_WCHAR32 `pkg-config --cflags --libs sdl2 --static` `pkg-config --cflags --libs gtk+-3.0` `pkg-config --cflags --libs gio-2.0` `pkg-config --cflags --libs glib-2.0` -lX11 -lGL -lc -lpthread -fPIC
elif [ $(uname) = "DragonFly" ]; then
 g++ "ImFileDialog.cpp" "imgui.cpp" "imgui_impl_sdl.cpp" "imgui_impl_opengl2.cpp" "imgui_draw.cpp" "imgui_tables.cpp" "imgui_widgets.cpp" "msgbox/imguial_msgbox.cpp" "../../../../shared/apifilesystem/filesystem.cpp" "filedialogs.cpp" "../../../../shared/lunasvg/liblunasvg.a" -o "/tmp/stigma.so" -std=c++17 -DIFD_SHARED_LIBRARY -shared -I../../../../shared/apifilesystem -I../../../../shared -Wno-format-security -I. -L../../../../shared/lunasvg -DIMGUI_USE_WCHAR32 -static-libgcc -static-libstdc++ `pkg-config --cflags --libs sdl2 --static` `pkg-config --cflags --libs gtk+-3.0` `pkg-config --cflags --libs gio-2.0` `pkg-config --cflags --libs glib-2.0` -lX11 -lGL -lc -lpthread -fPIC
elif [ $(uname) = "NetBSD" ]; then
 g++ "ImFileDialog.cpp" "imgui.cpp" "imgui_impl_sdl.cpp" "imgui_impl_opengl2.cpp" "imgui_draw.cpp" "imgui_tables.cpp" "imgui_widgets.cpp" "msgbox/imguial_msgbox.cpp" "../../../../shared/apifilesystem/filesystem.cpp" "filedialogs.cpp" "../../../../shared/lunasvg/liblunasvg.a" -o "/tmp/stigma.so" -std=c++17 -DIFD_SHARED_LIBRARY -shared -I../../../../shared/apifilesystem -I../../../../shared -Wno-format-security -I. -L../../../../shared/lunasvg -DIMGUI_USE_WCHAR32 -static-libgcc `pkg-config --cflags --libs sdl2 --static` `pkg-config --cflags --libs gtk+-3.0` `pkg-config --cflags --libs gio-2.0` `pkg-config --cflags --libs glib-2.0` -lX11 -lGL -lc -lpthread -fPIC
elif [ $(uname) = "OpenBSD" ]; then
 clang++ "ImFileDialog.cpp" "imgui.cpp" "imgui_impl_sdl.cpp" "imgui_impl_opengl2.cpp" "imgui_draw.cpp" "imgui_tables.cpp" "imgui_widgets.cpp" "msgbox/imguial_msgbox.cpp" "../../../../shared/apifilesystem/filesystem.cpp" "filedialogs.cpp" "../../../../shared/lunasvg/liblunasvg.a" -o "/tmp/stigma.so" -std=c++17 -DIFD_SHARED_LIBRARY -shared -I../../../../shared/apifilesystem -I../../../../shared -Wno-format-security -I. -L../../../../shared/lunasvg -DIMGUI_USE_WCHAR32 -I/usr/local/include `pkg-config --cflags --libs sdl2 --static` `pkg-config --cflags --libs gtk+-3.0` `pkg-config --cflags --libs gio-2.0` `pkg-config --cflags --libs glib-2.0` -lX11 -lGL -lc -lkvm -lpthread -fPIC
elif [ $(uname) = "SunOS" ]; then
 export PKG_CONFIG_PATH=/usr/lib/64/pkgconfig && g++ "ImFileDialog.cpp" "imgui.cpp" "imgui_impl_sdl.cpp" "imgui_impl_opengl2.cpp" "imgui_draw.cpp" "imgui_tables.cpp" "imgui_widgets.cpp" "msgbox/imguial_msgbox.cpp" "../../../../shared/apifilesystem/filesystem.cpp" "filedialogs.cpp" "../../../../shared/lunasvg/liblunasvg.a" -o "/tmp/stigma.so" -std=c++17 -DIFD_SHARED_LIBRARY -shared -I../../../../shared/apifilesystem -I../../../../shared -Wno-format-security -I. -L../../../../shared/lunasvg -DIMGUI_USE_WCHAR32 -static-libgcc `pkg-config --cflags --libs sdl2 --static` `pkg-config --cflags --libs gtk+-3.0` `pkg-config --cflags --libs gio-2.0` `pkg-config --cflags --libs glib-2.0` -lX11 -lGL -lc -lpthread -fPIC
else
 g++ "ImFileDialog.cpp" "imgui.cpp" "imgui_impl_sdl.cpp" "imgui_impl_opengl2.cpp" "imgui_draw.cpp" "imgui_tables.cpp" "imgui_widgets.cpp" "msgbox/imguial_msgbox.cpp" "../../../../shared/apifilesystem/filesystem.cpp" "filedialogs.cpp" -o "C:/Windows/Temp/stigma.dll" -std=c++17 -DIFD_SHARED_LIBRARY -shared -I../../../../shared/apifilesystem -I../../../../shared -I. -D_UNICODE -DUNICODE -DIMGUI_USE_WCHAR32 -static-libgcc -static-libstdc++ -static `pkg-config --cflags --libs sdl2 --static` -lopengl32 -lshell32 -fPIC
fi
