#!/bin/sh
# build shared library
export STIGMA_PATH=`pwd`;
cd "/tmp"
if [ `uname` = "Darwin" ]; then
 clang++ -c "$STIGMA_PATH/Widget_Systems/SDL/ImFileDialog.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui_impl_sdl.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui_impl_sdlrenderer.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui_draw.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui_tables.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui_widgets.cpp" "$STIGMA_PATH/Widget_Systems/SDL/msgbox/imguial_msgbox.cpp" "$STIGMA_PATH/../../shared/apifilesystem/filesystem.cpp" "$STIGMA_PATH/Widget_Systems/SDL/filedialogs.cpp" -std=c++17 -DIFD_SHARED_LIBRARY -shared -I"$STIGMA_PATH/../../shared/apifilesystem" -I"$STIGMA_PATH/../../shared" -Wno-format-security -I"$STIGMA_PATH" -DIMGUI_USE_WCHAR32 -I/opt/local/include -I/opt/local/include/SDL2 -ObjC++ -fPIC -arch arm64 -arch x86_64 -fPIC
 ar rc "/tmp/stigma.a" "/tmp/ImFileDialog.o" "/tmp/imgui.o" "/tmp/imgui_impl_sdl.o" "/tmp/imgui_impl_sdlrenderer.o" "/tmp/imgui_draw.o" "/tmp/imgui_tables.o" "/tmp/imgui_widgets.o" "/tmp/imguial_msgbox.o" "/tmp/filesystem.o" "/tmp/filedialogs.o"
elif [ $(uname) = "Linux" ]; then
 g++ -c "$STIGMA_PATH/Widget_Systems/SDL/ImFileDialog.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui_impl_sdl.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui_impl_sdlrenderer.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui_draw.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui_tables.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui_widgets.cpp" "$STIGMA_PATH/Widget_Systems/SDL/msgbox/imguial_msgbox.cpp" "$STIGMA_PATH/../../shared/apifilesystem/filesystem.cpp" "$STIGMA_PATH/Widget_Systems/SDL/filedialogs.cpp" -std=c++17 -DIFD_SHARED_LIBRARY -shared -I"$STIGMA_PATH/../../shared/apifilesystem" -I"$STIGMA_PATH/../../shared" -Wno-format-security -I"$STIGMA_PATH" -DIMGUI_USE_WCHAR32 `pkg-config --cflags sdl2 --static` `pkg-config --cflags gtk+-3.0` `pkg-config --cflags gio-2.0` `pkg-config --cflags glib-2.0` -fPIC
 ar rc "/tmp/stigma.a"  "/tmp/ImFileDialog.o" "/tmp/imgui.o" "/tmp/imgui_impl_sdl.o" "/tmp/imgui_impl_sdlrenderer.o" "/tmp/imgui_draw.o" "/tmp/imgui_tables.o" "/tmp/imgui_widgets.o" "/tmp/imguial_msgbox.o" "/tmp/filesystem.o" "/tmp/filedialogs.o"
elif [ $(uname) = "FreeBSD" ]; then
 clang++ -c "$STIGMA_PATH/Widget_Systems/SDL/ImFileDialog.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui_impl_sdl.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui_impl_sdlrenderer.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui_draw.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui_tables.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui_widgets.cpp" "$STIGMA_PATH/Widget_Systems/SDL/msgbox/imguial_msgbox.cpp" "$STIGMA_PATH/../../shared/apifilesystem/filesystem.cpp" "$STIGMA_PATH/Widget_Systems/SDL/filedialogs.cpp" -std=c++17 -DIFD_SHARED_LIBRARY -shared -I"$STIGMA_PATH/../../shared/apifilesystem" -I"$STIGMA_PATH/../../shared" -Wno-format-security -I"$STIGMA_PATH" -DIMGUI_USE_WCHAR32 `pkg-config --cflags sdl2 --static` `pkg-config --cflags gtk+-3.0` `pkg-config --cflags gio-2.0` `pkg-config --cflags glib-2.0` -fPIC
  ar rc "/tmp/stigma.a"  "/tmp/ImFileDialog.o" "/tmp/imgui.o" "/tmp/imgui_impl_sdl.o" "/tmp/imgui_impl_sdlrenderer.o" "/tmp/imgui_draw.o" "/tmp/imgui_tables.o" "/tmp/imgui_widgets.o" "/tmp/imguial_msgbox.o" "/tmp/filesystem.o" "/tmp/filedialogs.o"
elif [ $(uname) = "DragonFly" ]; then
 g++ -c "$STIGMA_PATH/Widget_Systems/SDL/ImFileDialog.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui_impl_sdl.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui_impl_sdlrenderer.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui_draw.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui_tables.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui_widgets.cpp" "$STIGMA_PATH/Widget_Systems/SDL/msgbox/imguial_msgbox.cpp" "$STIGMA_PATH/../../shared/apifilesystem/filesystem.cpp" "$STIGMA_PATH/Widget_Systems/SDL/filedialogs.cpp" -std=c++17 -DIFD_SHARED_LIBRARY -shared -I"$STIGMA_PATH/../../shared/apifilesystem" -I"$STIGMA_PATH/../../shared" -Wno-format-security -I"$STIGMA_PATH" -DIMGUI_USE_WCHAR32 `pkg-config --cflags sdl2 --static` `pkg-config --cflags gtk+-3.0` `pkg-config --cflags gio-2.0` `pkg-config --cflags glib-2.0` -fPIC
  ar rc "/tmp/stigma.a"  "/tmp/ImFileDialog.o" "/tmp/imgui.o" "/tmp/imgui_impl_sdl.o" "/tmp/imgui_impl_sdlrenderer.o" "/tmp/imgui_draw.o" "/tmp/imgui_tables.o" "/tmp/imgui_widgets.o" "/tmp/imguial_msgbox.o" "/tmp/filesystem.o" "/tmp/filedialogs.o"
elif [ $(uname) = "NetBSD" ]; then
 g++ -c "$STIGMA_PATH/Widget_Systems/SDL/ImFileDialog.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui_impl_sdl.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui_impl_sdlrenderer.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui_draw.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui_tables.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui_widgets.cpp" "$STIGMA_PATH/Widget_Systems/SDL/msgbox/imguial_msgbox.cpp" "$STIGMA_PATH/../../shared/apifilesystem/filesystem.cpp" "$STIGMA_PATH/Widget_Systems/SDL/filedialogs.cpp" -std=c++17 -DIFD_SHARED_LIBRARY -shared -I"$STIGMA_PATH/../../shared/apifilesystem" -I"$STIGMA_PATH/../../shared" -Wno-format-security -I"$STIGMA_PATH" -DIMGUI_USE_WCHAR32 `pkg-config --cflags sdl2 --static` `pkg-config --cflags gtk+-3.0` `pkg-config --cflags gio-2.0` `pkg-config --cflags glib-2.0` -fPIC
  ar rc "/tmp/stigma.a"  "/tmp/ImFileDialog.o" "/tmp/imgui.o" "/tmp/imgui_impl_sdl.o" "/tmp/imgui_impl_sdlrenderer.o" "/tmp/imgui_draw.o" "/tmp/imgui_tables.o" "/tmp/imgui_widgets.o" "/tmp/imguial_msgbox.o" "/tmp/filesystem.o" "/tmp/filedialogs.o"
elif [ $(uname) = "OpenBSD" ]; then
 clang++ -c "$STIGMA_PATH/Widget_Systems/SDL/ImFileDialog.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui_impl_sdl.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui_impl_sdlrenderer.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui_draw.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui_tables.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui_widgets.cpp" "$STIGMA_PATH/Widget_Systems/SDL/msgbox/imguial_msgbox.cpp" "$STIGMA_PATH/../../shared/apifilesystem/filesystem.cpp" "$STIGMA_PATH/Widget_Systems/SDL/filedialogs.cpp" -std=c++17 -DIFD_SHARED_LIBRARY -shared -I"$STIGMA_PATH/../../shared/apifilesystem" -I"$STIGMA_PATH/../../shared" -Wno-format-security -I"$STIGMA_PATH" -DIMGUI_USE_WCHAR32 `pkg-config --cflags sdl2 --static` `pkg-config --cflags gtk+-3.0` `pkg-config --cflags gio-2.0` `pkg-config --cflags glib-2.0` -fPIC
 ar rc "/tmp/stigma.a"  "/tmp/ImFileDialog.o" "/tmp/imgui.o" "/tmp/imgui_impl_sdl.o" "/tmp/imgui_impl_sdlrenderer.o" "/tmp/imgui_draw.o" "/tmp/imgui_tables.o" "/tmp/imgui_widgets.o" "/tmp/imguial_msgbox.o" "/tmp/filesystem.o" "/tmp/filedialogs.o"
elif [ $(uname) = "SunOS" ]; then
 export PKG_CONFIG_PATH=/usr/lib/64/pkgconfig && g++ -c "$STIGMA_PATH/Widget_Systems/SDL/ImFileDialog.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui_impl_sdl.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui_impl_sdlrenderer.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui_draw.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui_tables.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui_widgets.cpp" "$STIGMA_PATH/Widget_Systems/SDL/msgbox/imguial_msgbox.cpp" "$STIGMA_PATH/../../shared/apifilesystem/filesystem.cpp" "$STIGMA_PATH/Widget_Systems/SDL/filedialogs.cpp" -std=c++17 -DIFD_SHARED_LIBRARY -shared -I"$STIGMA_PATH/../../shared/apifilesystem" -I"$STIGMA_PATH/../../shared" -Wno-format-security -I"$STIGMA_PATH" -DIMGUI_USE_WCHAR32 `pkg-config --cflags sdl2 --static` `pkg-config --cflags gtk+-3.0` `pkg-config --cflags gio-2.0` `pkg-config --cflags glib-2.0` -fPIC
 ar rc "/tmp/stigma.a" "/tmp/ImFileDialog.o" "/tmp/imgui.o" "/tmp/imgui_impl_sdl.o" "/tmp/imgui_impl_sdlrenderer.o" "/tmp/imgui_draw.o" "/tmp/imgui_tables.o" "/tmp/imgui_widgets.o" "/tmp/imguial_msgbox.o" "/tmp/filesystem.o" "/tmp/filedialogs.o"
else
 g++ -c "$STIGMA_PATH/Widget_Systems/SDL/ImFileDialog.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui_impl_sdl.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui_impl_sdlrenderer.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui_draw.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui_tables.cpp" "$STIGMA_PATH/Widget_Systems/SDL/imgui_widgets.cpp" "$STIGMA_PATH/Widget_Systems/SDL/msgbox/imguial_msgbox.cpp" "$STIGMA_PATH/../../shared/apifilesystem/filesystem.cpp" "$STIGMA_PATH/Widget_Systems/SDL/filedialogs.cpp" -std=c++17 -DIFD_SHARED_LIBRARY -shared -I"$STIGMA_PATH/../../shared/apifilesystem" -I"$STIGMA_PATH/../../shared" -I"$STIGMA_PATH" -D_UNICODE -DUNICODE -DIMGUI_USE_WCHAR32 `pkg-config --cflags sdl2 --static` -static-libgcc -static-libstdc++ -static -fPIC
 ar rc "/tmp/stigma.a" "/tmp/ImFileDialog.o" "/tmp/imgui.o" "/tmp/imgui_impl_sdl.o" "/tmp/imgui_impl_sdlrenderer.o" "/tmp/imgui_draw.o" "/tmp/imgui_tables.o" "/tmp/imgui_widgets.o" "/tmp/imguial_msgbox.o" "/tmp/filesystem.o" "/tmp/filedialogs.o"
fi
