include Graphics_Systems/OpenGLES/Makefile
include Graphics_Systems/OpenGL3-OpenGLES3/Makefile
override CXXFLAGS += -IGraphics_Systems/OpenGLES3/glad/ -DENIGMA_GRAPHICS_OPENGLES3
SOURCES += $(wildcard Graphics_Systems/OpenGLES3/*.cpp) Graphics_Systems/OpenGLES3/glad/glad.c

SHADER_VERSION := Graphics_Systems/OpenGLES3/version.glsl
