SOURCES += $(wildcard Widget_Systems/Win32/*.cpp)
RESOURCES += Widget_Systems/Win32/getstring.rc Widget_Systems/Win32/getlogin.rc Widget_Systems/Win32/showinfo.rc Widget_Systems/Win32/showmessageext.rc
LDLIBS += -lcomctl32 -luuid -lole32