edition = "2024";
option features.field_presence = EXPLICIT;
option features.enforce_naming_style = STYLE_LEGACY;
package buffers.resources;

import "options.proto";

message Font {
  message Glyph {
    uint32 character = 1;
    
    // Rectangle in the sprite font texture given by `image`.
    uint32 x = 2;
    uint32 y = 3; 
    uint32 width = 4 [(gmx) = "w"];
    uint32 height = 5 [(gmx) = "h"];
    
    // Kerning offsets. Round on .5 after summing.
    double origin = 6 [(gmx) = "offset"]; 
    double baseline = 7;
    double advance = 8 [(gmx) = "shift"];
  }

  message Range {
    int32 min = 1 [(gmx) = "GMX_SPLIT/0"];
    int32 max = 2 [(gmx) = "GMX_SPLIT/1"];
  }

  int32 id = 2 [(gmx) = "GMX_DEPRECATED"];

  string font_name = 3 [(gmx) = "name"];
  int32 size = 4;
  bool bold = 5;
  bool italic = 6;

  repeated Range ranges = 7 [(gmx) = "ranges/range0"];
  repeated Glyph glyphs = 8 [(gmx) = "glyphs/glyph"];
  
  bool renderhq = 10;
  uint32 charset = 11;
  uint32 antialias = 12 [(gmx) = "aa"];
  bool include_ttf = 13 [(gmx) = "includeTTF"];
  string ttf_file = 14 [(gmx) = "TTFName"]; 
  int32 texture_group = 15 [(gmx) = "texgroups/texgroup0"];
  string image = 16;
}
