edition = "2024";
option features.field_presence = EXPLICIT;
option features.enforce_naming_style = STYLE_LEGACY;
package buffers.resources;

import "options.proto";
import "google/protobuf/cpp_features.proto";

message Room {
  int32 id = 29 [(gmx) = "GMX_DEPRECATED"];

  string caption = 1;
  uint32 width = 2 [(yyp) = "roomSettings/Width"];
  uint32 height = 3 [(yyp) = "roomSettings/Height"];
  uint32 hsnap = 4;
  uint32 vsnap = 5;
  bool isometric = 6;
  uint32 speed = 27;
  bool persistent = 7 [(yyp) = "roomSettings/persistent"];
  int32 color = 8 [(gmx) = "colour"];
  bool show_color = 9 [(gmx) = "showcolour"];
  string creation_code = 10;
  bool enable_views = 11 [(gmx) = "enableViews", (yyp) = "viewSettings/enableViews"];
  bool clear_view_background = 12 [(gmx) = "clearViewBackground", (yyp) = "viewSettings/clearViewBackground"];
  bool clear_display_buffer = 13 [(gmx) = "clearDisplayBuffer", (yyp) = "viewSettings/clearDisplayBuffer"];

  message Background {
    bool visible = 1;
    bool foreground = 2;
    string background_name = 3 [(resource_ref)="background", (gmx) = "name", features.(pb.cpp).string_type = STRING];
    int32 x = 4;
    int32 y = 5;
    bool htiled = 6;
    bool vtiled = 7;
    double hspeed = 8;
    double vspeed = 9;
    bool stretch = 10;
    int32 color = 11 [(default_value) = "16777215"];
    double alpha = 12 [(default_value) = "1.0"];
  }

  repeated Background backgrounds = 15 [(gmx) = "backgrounds/background"];

  message View {
    bool visible = 1;
    int32 xview = 2;
    int32 yview = 3;
    uint32 wview = 4;
    uint32 hview = 5;
    int32 xport = 6;
    int32 yport = 7;
    uint32 wport = 8;
    uint32 hport = 9;
    int32 hborder = 10;
    int32 vborder = 11;
    double hspeed = 12;
    double vspeed = 13;
    string object_following = 14 [(resource_ref)="object", (gmx) = "objName", features.(pb.cpp).string_type = STRING];
  }

  repeated View views = 16 [(gmx) = "views/view", (yyp) = "views"];

  message Instance {
    string name = 1;
    int32 id = 2 [(id_start) = 100001];
    string object_type = 3 [(resource_ref)="object", (gmx) = "objName", features.(pb.cpp).string_type = STRING];
    double x = 4;
    double y = 5;
    double z = 6;
    string creation_code = 7;
    string initialization_code = 14;
    double xscale = 8 [(default_value) = "1", (gmx) = "scaleX"];
    double yscale = 9 [(default_value) = "1", (gmx) = "scaleY"];
    double zscale = 10 [(default_value) = "1", (gmx) = "scaleY"];
    double rotation  = 11;
    double zrotation = 12;
    int32 color = 13 [(default_value) = "16777215", (gmx) = "colour"];

    message EditorSettings {
      bool locked = 1;
    }

    EditorSettings editor_settings = 31;
  }

  repeated Instance instances = 17 [(gmx) = "instances/instance"];

  message Tile {
    string name = 1;
    int32 id = 2 [(id_start) = 10000001];
    string background_name = 3 [(resource_ref)="background", (gmx) = "bgName", features.(pb.cpp).string_type = STRING];
    double x = 4;
    double y = 5;
    int32 xoffset = 6 [(gmx) = "xo"];
    int32 yoffset = 7 [(gmx) = "yo"];
    uint32 width = 8 [(gmx) = "w"];
    uint32 height = 9 [(gmx) = "h"];
    int32 depth = 10;
    double xscale = 11 [(default_value) = "1.0", (gmx) = "scaleX"];
    double yscale = 12 [(default_value) = "1.0", (gmx) = "scaleY"];
    int32 color = 13 [(default_value) = "16777215", (gmx) = "colour"];
    double alpha = 14 [(default_value) = "1.0"];

    message EditorSettings {
      bool locked = 1;
    }

    EditorSettings editor_settings = 31;
  }

  repeated Tile tiles = 18 [(gmx) = "tiles/tile"];

  message Layer {
    string name = 1;
    int32 id = 2;
    int32 depth = 3;
    bool visible = 4;

    repeated Instance instances = 5;
    repeated Tile tiles = 6;
  }

  repeated Layer layers = 20;

  message RoomPhysicsSettings {
    bool use_physics = 1 [(gmx) = "PhysicsWorld"];
    int32 phy_world_top = 2 [(gmx) = "PhysicsWorldTop"];
    int32 phy_world_left = 3 [(gmx) = "PhysicsWorldLeft"];
    int32 phy_world_right = 4 [(gmx) = "PhysicsWorldRight"];
    int32 phy_world_bottom = 5 [(gmx) = "PhysicsWorldBottom"];
    double phy_world_xgravity = 6 [(gmx) = "PhysicsWorldGravityX"];
    double phy_world_ygravity = 7 [(gmx) = "PhysicsWorldGravityY"];
    double phy_world_pixel_meters = 8 [(gmx) = "PhysicsWorldPixToMeters"];
  }

  RoomPhysicsSettings physics_settings = 19 [(gmx) = "EGM_NESTED"];

}
