edition = "2024";
option features.field_presence = EXPLICIT;
option features.enforce_naming_style = STYLE_LEGACY;
package buffers.resources;

import "options.proto";

message Settings {
  API api = 1;
  Compiler compiler = 2;
  General general = 3;
  Graphics graphics = 4;
  Windowing windowing = 8;
  Info info = 5;
  Installer installer = 6;
  Deployment deployment = 7;
  Shortcuts shortcuts = 9;
}

message API {
  string target_audio = 1;
  string target_platform = 2;
  string target_compiler = 3;
  string target_graphics = 4;
  string target_widgets = 5;
  string target_collision = 6;
  string target_network = 7;
  repeated string extensions = 8;
}

message Compiler {
  uint32 inherit_strings = 1;
  uint32 inherit_escapes = 2;
  uint32 inherit_increment = 3;
  uint32 inherit_equivalence = 4;
  uint32 inherit_literals = 5;
  uint32 inherit_negatives = 6;
  uint32 compliance_mode = 7;
  repeated string keyword_blacklist = 8;

  string eobjs_directory = 9;
  string codegen_directory = 10;
  bool inherit_objects = 11;
  bool automatic_semicolons = 12;

  uint32 graphics_angular_unit = 13;
  uint32 graphics_scalar_precision = 14;

  uint32 collision_angular_unit = 15;
  uint32 collision_scalar_precision = 16;

  uint32 audio_angular_unit = 17;
  uint32 audio_scalar_precision = 18;

  bool treat_uninitialized_vars_as_zero = 19;
}

message General {
  uint64 game_id = 1 [(gmx) = "option_gameid"];
  string game_guid = 2 [(gmx) = "option_gameguid"];
  string display_name = 4 [(gmx) = "option_display_name"];
  uint32 version_major = 5 [(gmx) = "option_version_major"];
  uint32 version_minor = 6 [(gmx) = "option_version_minor"];
  uint32 version_release = 7 [(gmx) = "option_version_release"];
  uint32 version_build = 8 [(gmx) = "option_version_build"];
  string company = 9 [(gmx) = "option_version_company"];
  string product = 10 [(gmx) = "option_version_product"];
  string copyright = 11 [(gmx) = "option_version_copyright"];
  string description = 12 [(gmx) = "option_version_description"];
  bool show_cursor = 13 [(default_value) = "true", (gmx) = "option_showcursor"];
  string game_icon = 14 [(gmx) = "option_windows_game_icon"];
  string splash_screen = 15 [(gmx) = "option_windows_splash_screen"];
  bool show_splash_screen = 16 [(gmx) = "option_windows_use_splash"];
  uint32 sleep_margin = 17 [(gmx) = "option_windows_sleep_margin"];
  string save_data_location = 18 [(gmx) = "option_windows_save_location"];
  bool menu_dock = 19 [(gmx) = "option_mac_menu_dock"];
}

message Graphics {
  int32 color_outside_room_region = 1 [(gmx) = "option_windowcolor"];
  bool allow_fullscreen_change = 2 [(gmx) = "option_screenkey"];
  bool interpolate_textures = 3 [(gmx) = "option_interpolate"];
  bool force_software_vertex_processing = 4 [(gmx) = ""];
  bool use_synchronization = 6 [(gmx) = ""];
  double view_scale = 11 [(gmx) = "option_scale"];
  bool create_textures_on_demand = 12 [(gmx) = "option_windows_create_textures_on_demand"];
  bool alternate_synchronization_method = 13 [(gmx) = "option_windows_alternate_sync_method"];

  enum VertexBufferMethod { FAST = 0; COMPATIBLE = 1; MOST_COMPATIBLE = 2; }
  VertexBufferMethod vertex_buffer_method = 14 [(gmx) = "option_windows_vertex_buffer_method2"];

  uint32 texture_page_size = 15 [(gmx) = "option_windows_texture_page"];
  bool enable_hidpi = 16 [(gmx) = "option_mac_enable_retina"];
}

message Windowing {
  bool is_sizeable = 1 [(gmx) = "option_sizeable"];
  bool start_in_fullscreen = 2 [(gmx) = "option_fullscreen"];
  bool show_border = 3 [(default_value) = "true", (gmx) = "option_noborder"];
  bool show_icons = 4 [(default_value) = "true", (gmx) = "option_nobuttons"];
  bool stay_on_top = 5 [(gmx) = "option_stayontop"];
  bool freeze_on_lose_focus = 6 [(gmx) = "option_freeze"];
  bool treat_close_as_escape = 7 [(default_value) = "true"];
}

message Info {
  string author_name = 1 [(gmx) = "option_author"];
  string author_email = 2 [(gmx) = "option_linux_maintainer_email"];
  string website = 3 [(gmx) = "option_linux_homepage"];
  string version = 4 [(gmx) = "option_version"];
  uint32 last_changed = 5 [(gmx) = "option_lastchanged"];
  string information = 6 [(gmx) = "option_information"];
}

message Installer {
  string finished_image = 1 [(gmx) = "option_windows_runner_finished"];
  string header_image = 2 [(gmx) = "option_windows_runner_header"];
  string script = 3 [(gmx) = "option_windows_nsis_file"];
  string license_agreement = 4 [(gmx) = "option_windows_license"];
}

message Deployment {
  string app_id = 1 [(gmx) = "option_mac_app_id"];
  string app_output = 2 [(gmx) = "option_mac_output_dir"];
  string team_identifier = 3 [(gmx) = "option_mac_team_id"];
  bool enable_appstore_build = 4 [(gmx) = "option_mac_create_app_store"];
  bool allow_incoming_connections = 5 [(gmx) = "option_mac_appstore_incoming_allow"];
  bool allow_outgoing_connections = 6 [(gmx) = "option_mac_appstore_outgoing_allow"];
  string app_category = 7 [(gmx) = "option_mac_app_category"];
  string signing_identity = 8 [(gmx) = "option_mac_signing_identity"];
}

message Shortcuts {
  bool let_escape_end_game = 1 [(default_value) = "true"];
  bool let_f4_switch_fullscreen = 2;
  bool let_f1_show_game_info = 3;
  bool let_f9_screenshot = 4;
  bool let_f5_save_f6_load = 5;
}
