edition = "2024";
option features.field_presence = EXPLICIT;
option features.enforce_naming_style = STYLE_LEGACY;
package buffers.resources;

import "options.proto";

message Sound {
  int32 id = 2 [(gmx) = "GMX_DEPRECATED"];

  bool preload = 3;
  double pan = 4;
  double volume = 5 [(gmx) = "volume/volume"];
  string file_name = 6 [(gmx) = "data"];
  string file_extension = 7 [(gmx) = "extension"];

  enum Kind { NORMAL = 0; BACKGROUND_MUSIC = 1; THREE_DIMENSIONAL = 2; MULTIMEDIA_PLAYER = 3; }

  Kind kind = 8;

  enum Type { MONO = 0; STEREO = 1; POSITIONAL = 2; }

  Type type = 9 [(gmx) = "types/type"];

  string data = 10 [(gmx) = "origname", (file_path) = true, (file_kind) = AUDIO];

  int32 effects = 11;
  uint32 bit_rate = 12 [(gmx) = "bitRates/bitRate"];
  uint32 sample_rate = 13 [(gmx) = "sampleRates/sampleRate"];
  uint32 bit_depth = 14 [(gmx) = "bitDepths/bitDepth"];
  bool compressed = 15;
  bool streamed = 16;
  bool uncompress_on_load = 17 [(gmx) = "uncompressOnLoad"];
  int32 audio_group = 18 [(gmx) = "audioGroup"];
}
