/********************************************************************************\
**                                                                              **
**  Copyright (C) 2008 Josh Ventura                                             **
**                                                                              **
**  This file is a part of the ENIGMA Development Environment.                  **
**                                                                              **
**                                                                              **
**  ENIGMA is free software: you can redistribute it and/or modify it under the **
**  terms of the GNU General Public License as published by the Free Software   **
**  Foundation, version 3 of the license or any later version.                  **
**                                                                              **
**  This application and its source code is distributed AS-IS, WITHOUT ANY      **
**  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS   **
**  FOR A PARTICULAR PURPOSE. See the GNU General Public License for more       **
**  details.                                                                    **
**                                                                              **
**  You should have recieved a copy of the GNU General Public License along     **
**  with this code. If not, see <http://www.gnu.org/licenses/>                  **
**                                                                              **
**  ENIGMA is an environment designed to create games and other programs with a **
**  high-level, fully compilable language. Developers of ENIGMA or anything     **
**  associated with ENIGMA are in no way responsible for its users or           **
**  applications created by its users, or damages caused by the environment     **
**  or programs made in the environment.                                        **
**                                                                              **
\********************************************************************************/

//This file was generated by the ENIGMA Development Environment.
//Editing it is a sign of a certain medical condition. We're not sure which one.

#include "Platforms/xlib/include.h"
#include "Graphics_Systems/OpenGL/include.h"
#include "Audio_Systems/OpenAL/include.h"
#include "Collision_Systems/BBox/include.h"
#include "Widget_Systems/None/include.h"

// Extensions selected by user
#include "Universal_System/Extensions/Alarms/include.h"
#include "Universal_System/Extensions/Alarms/implement.h"
#include "Universal_System/Extensions/Timelines/include.h"
#include "Universal_System/Extensions/Paths/include.h"
#include "Universal_System/Extensions/Paths/implement.h"
#include "Universal_System/Extensions/MotionPlanning/include.h"
#include "Universal_System/Extensions/MotionPlanning/implement.h"
#include "Universal_System/Extensions/DateTime/include.h"
#include "Universal_System/Extensions/DateTime/implement.h"
#include "Universal_System/Extensions/DataStructures/include.h"
#include "Universal_System/Extensions/DataStructures/implement.h"

