include Graphics_Systems/OpenGL/Makefile
override CXXFLAGS += -IGraphics_Systems/OpenGLES2/glad/ -DglClearDepth=glClearDepthf -DGL_BGRA=GL_BGRA_EXT -DENIGMA_GRAPHICS_OPENGLES2
SOURCES += $(wildcard Graphics_Systems/OpenGLES2/*.cpp) $(wildcard Graphics_Systems/OpenGL2/*.cpp) Graphics_Systems/OpenGLES2/glad/glad.c
