include Graphics_Systems/OpenGLES/Makefile
include Graphics_Systems/OpenGL2-OpenGLES2/Makefile
override CXXFLAGS += -IGraphics_Systems/OpenGLES2/glad/ -DENIGMA_GRAPHICS_OPENGLES2
SOURCES += $(wildcard Graphics_Systems/OpenGLES2/*.cpp) Graphics_Systems/OpenGLES2/glad/glad.c

SHADER_VERSION := Graphics_Systems/OpenGLES2/version.glsl
