SOURCES += Universal_System/Extensions/BasicGUI/buttons.cpp
SOURCES += Universal_System/Extensions/BasicGUI/windows.cpp
SOURCES += Universal_System/Extensions/BasicGUI/skins.cpp
SOURCES += Universal_System/Extensions/BasicGUI/toggles.cpp