SOURCES += Universal_System/Extensions/BasicGUI/buttons.cpp
SOURCES += Universal_System/Extensions/BasicGUI/windows.cpp
SOURCES += Universal_System/Extensions/BasicGUI/skins.cpp
SOURCES += Universal_System/Extensions/BasicGUI/toggles.cpp
SOURCES += Universal_System/Extensions/BasicGUI/sliders.cpp
SOURCES += Universal_System/Extensions/BasicGUI/styles.cpp
SOURCES += Universal_System/Extensions/BasicGUI/labels.cpp
SOURCES += Universal_System/Extensions/BasicGUI/groups.cpp