ifeq ($(GMODE), Debug)
	SOURCES += Bridges/OpenGLDebug/OpenGLDebug.cpp
	CLEANDEPS += $(OBJDIR)/Bridges/OpenGLDebug/OpenGLDebug.cpp
endif

$(OBJDIR)/Bridges/OpenGLDebug/OpenGLDebug.o: $(CODEGEN)/API_Switchboard.h
