include $(SHARED_SRC_DIR)/tinyfiledialogs/Makefile

SOURCES += Widget_Systems/General/tinyfiledialogs/dialogs.cpp
SOURCES += Widget_Systems/General/tinyfiledialogs/dialogs.m
SOURCES += Widget_Systems/OsaScript/dialogs.cpp
