SOURCES += $(wildcard Bridges/xlib-None/*.cpp) Platforms/None/fillin.cpp Graphics_Systems/General/GScolors.cpp
SOURCES := $(filter-out $(wildcard Universal_System/bufferstruct.cpp), $(SOURCES)) 
SOURCES := $(filter-out $(wildcard Platforms/xlib/*.cpp), $(SOURCES))
