SOURCES += $(wildcard Audio_Systems/DirectSound/*.cpp)
override LDLIBS += -ldsound -ldxguid -lwinmm

$(OBJDIR)/Audio_Systems/DirectSound/DSbasic.o: $(CODEGEN)/API_Switchboard.h
$(OBJDIR)/Audio_Systems/DirectSound/DSadvanced.o: $(CODEGEN)/API_Switchboard.h
