#include "DIRECTX10Std.h"
#include "Info/graphics_info.h" 
#include "../General/DXsprite.h"
#include "../General/DXbackground.h"
#include "DX10vertexbuffer.h"
#include "DX10shader.h"
#include "../General/DXtextures.h"
#include "DX10material.h"
#include "DX10model.h"

#include "../General/DXfont.h"
#include "../General/DXcurves.h"
#include "../General/DXsurface.h"
