# This shell script is to be run by ENIGMA Developers on Linux.
# It will generate a general-purpose Makefile containing a target
#    for every CPP file within two subdirectories of this folder.
# The generated Makefile should probably then be edited for target-specific files.
# The most obvious of these is standalone_*.cpp, which is removed automatically.

echo "#Awesome Makefile generated by ./genmake.sh: THIS SHOULD BE EDITED BY AN INTELLIGENT BEING." > Makefile
echo "# File consists of a lot of gobbledy followed by a target" >> Makefile;
echo "" >> Makefile;

echo "# DEBUG (faster compile)" >> Makefile;
echo "# SYMBOL_FLAGS       = -g" >> Makefile;
echo "# OPTIMIZATION_FLAGS =" >> Makefile;
echo "" >> Makefile;
echo "# RELEASE (faster runtime)" >> Makefile;
echo "SYMBOL_FLAGS       = -s # Strip symbol table" >> Makefile;
echo "OPTIMIZATION_FLAGS = -O2 # Optimize for speed" >> Makefile;
echo "# OPTIMIZATION_FLAGS = -Os # Optimize for size" >> Makefile;
echo "" >> Makefile;

for subdir in */ */*/ ./; #Iterate 
  do
    for file in $subdir*.cpp ;
      do
      {
        pathless="${file##*/}";
        if [[ $pathless == \** ]]; 
          then continue; 
          fi
        printf ".eobjs/${pathless%.cpp}.o: $file" >> Makefile;
        for i in `c_incl $file | gawk '/\/usr\/include/ { next } { print } '`;
        do
          printf " $i" >> Makefile;
        done;
        echo "" >> Makefile;
        
        echo "	-mkdir .eobjs" >> Makefile;
        echo "	g++ -Wall ${SYMBOL_FLAGS} ${OPTIMIZATION_FLAGS} -fPIC -c  $file		-o .eobjs/${pathless%.cpp}.o \$(FLAGS)"  >> Makefile;
      };
      done;
  done;

echo "" >> Makefile;
echo "# Nobody knows the trouble I've seen, no... no... nooo..." >> Makefile;
printf "link:" >> Makefile;
  for subdir in */ */*/ ./; #Iterate 
    do
      for file in $subdir*.cpp;
      do 
        pathless="${file##*/}";
        if [[ $pathless == \** ]]; 
          then continue; 
          fi
        if [[ $pathless == standalone_* ]]; 
          then continue; 
          fi
        printf " .eobjs/${pathless%.cpp}.o" >> Makefile; 
      done;
    done;
    echo "" >> Makefile;
  
  echo "	g++ -shared -fPIC .eobjs/*.o -o ../compileEGMf" >> Makefile;

echo "" >> Makefile;
echo "win windows: link" >> Makefile;
echo "	-move ../compileEGMf.exe ../compileEGMf" >> Makefile;
echo "	move ../compileEGMf ../compileEGMf.dll" >> Makefile;
echo "lin linux unix: link" >> Makefile;
echo "	mv ../compileEGMf ../libcompileEGMf.so" >> Makefile;

echo "" >> Makefile;
echo "clean:" >> Makefile;
echo "	rm -f .eobjs/*" >> Makefile;

echo "" >> Makefile;
