# This shell script is to be run by ENIGMA Developers on Linux.
# It will generate a general-purpose makefile containing a target
#    for every CPP file within two subdirectories of this folder.
# The generated makefile should probably then be edited for target-specific files.
# The most obvious of these is standalone_*.cpp, which is removed automatically.

echo "#Awesome makefile generated by ./genmake.sh: THIS SHOULD BE EDITED BY AN INTELLIGENT BEING." > makefile
echo "# File consists of a lot of gobbledy followed by a target" >> makefile;
echo "" >> makefile;

echo "# DEBUG (faster compile)" >> makefile;
echo "# SYMBOL_FLAGS       = -g" >> makefile;
echo "# OPTIMIZATION_FLAGS =" >> makefile;
echo "" >> makefile;
echo "# RELEASE (faster runtime)" >> makefile;
echo "SYMBOL_FLAGS       = -s # Strip symbol table" >> makefile;
echo "OPTIMIZATION_FLAGS = -O2 # Optimize for speed" >> makefile;
echo "# OPTIMIZATION_FLAGS = -Os # Optimize for size" >> makefile;
echo "" >> makefile;

for subdir in */ */*/ ./; #Iterate 
  do
    for file in $subdir*.cpp ;
      do
      {
        pathless="${file##*/}";
        if [[ $pathless == \** ]]; 
          then continue; 
          fi
        printf ".eobjs/${pathless%.cpp}.o:" >> makefile;
        for i in `c_incl $file | gawk '/\/usr\/include/ { next } { print } '`;
        do
          printf " $i" >> makefile;
        done;
        echo "" >> makefile;
        
        echo "	-mkdir .eobjs" >> makefile;
        echo "	g++ -Wall ${SYMBOL_FLAGS} ${OPTIMIZATION_FLAGS} -fPIC -c  $file		-o .eobjs/${pathless%.cpp}.o \$(FLAGS)"  >> makefile;
      };
      done;
  done;

echo "" >> makefile;
echo "# Nobody knows the trouble I've seen, no... no... nooo..." >> makefile;
printf "link:" >> makefile;
  for subdir in */ */*/ ./; #Iterate 
    do
      for file in $subdir*.cpp;
      do 
        pathless="${file##*/}";
        if [[ $pathless == \** ]]; 
          then continue; 
          fi
        if [[ $pathless == standalone_* ]]; 
          then continue; 
          fi
        printf " .eobjs/${pathless%.cpp}.o" >> makefile; 
      done;
    done;
    echo "" >> makefile;
  
  echo "	g++ -shared -fPIC .eobjs/*.o -o ../compileEGMf" >> makefile;

echo "" >> makefile;
echo "win windows: link" >> makefile;
echo "	move ../compileEGMf ../compileEGMf.dll" >> makefile;
echo "lin linux unix: link" >> makefile;
echo "	mv ../compileEGMf ../libcompileEGMf.so" >> makefile;

echo "" >> makefile;
echo "clean:" >> makefile;
echo "	rm -f .eobjs/*" >> makefile;

echo "" >> makefile;
