include $(SHARED_SRC_DIR)/tinyfiledialogs/Makefile

ifeq ($(TARGET-PLATFORM), MacOSX)
	SOURCES += Widget_Systems/TinyFileDialogs/dialogs-macos.cpp
endif

ifeq ($(TARGET-PLATFORM), Linux)
	SOURCES += Widget_Systems/TinyFileDialogs/dialogs-linux.cpp
endif
