SOURCES += $(wildcard Universal_System/*.cpp) $(wildcard Universal_System/Resources/*.cpp) $(wildcard Universal_System/Resources/Objects/*.cpp)
LDLIBS += -lz
CLEANDEPS += $(OBJDIR)/Universal_System/loading.o
