SOURCES += $(wildcard Universal_System/*.cpp) $(wildcard Universal_System/Object_Tiers/*.cpp)
override LDLIBS += -lz
override CXXFLAGS += -IUniversal_System/ -IUniversal_System/Object_Tiers
CLEANDEPS += $(OBJDIR)/Universal_System/loading.o
