game:
	-rm Platforms/Android/EnigmaAndroidGame/obj/local*/* # First of all, delete objects
	cd Platforms/Android/EnigmaAndroidGame/jni && /Users/alasdairmorrison/Documents/AndroidSDK/crystax/ndk-build

