game:
	-rm ENIGMAsystem/SHELL/Platforms/Android/EnigmaAndroidGame/obj/local*/* # First of all, delete objects
	cd ENIGMAsystem/SHELL/Platforms/Android/EnigmaAndroidGame/jni && /Users/alasdairmorrison/Documents/AndroidSDK/crystax/ndk-build

