# SHARED_INCLUDES += tinyfiledialogs (Best to just let them include tinyfiledialogs/tinyfiledialogs.h)
SHARED_SOURCES := $(SHARED_SOURCES) $(addprefix tinyfiledialogs/,$(call relative_wildcard,*.cpp))
